Repository githubschool/blue-moon, pull requests merged in 2020-04, with the labels that each got.

#14 change line 6
  _posts/0000-01-20-ramvee321.md
Labels: button-fix

#13 Add a descriptive caption
  _posts/0000-01-18-ericalloyd.md
Labels: button-fix

#23 Sr08003 raghav passion
  _posts/0000-01-14-sr08003.md
Labels: enhancement

#21 Update caption on line 6
  _posts/0000-01-17-SA07915.md
Labels: caption-fix

#16 Update the caption
  _posts/0000-01-02-veltcode.md
Labels: Release-2020

#19 Modify Caption
  _posts/0000-01-06-lavpersonal.md
Labels: caption-fix
